### ISSUE TITLE
Handle special case mutations

### ISSUE THREAD

**Issue by chrisamiller** [leylabdotorg/amlviz#13]
There are some genes where we want to segregate mutations by specific amino acid change when creating plots.  Examples:  DNMT3A (R882 vs Other muts),  FLT3 (ITD vs D835 v other)

There are a couple of options, as I see it:
1) define an "alias" or "mutational group" field that specifies these special cases and handles them as distinct entities
 
2) add a UI element (pulldown?) that shows all of the mutations for a specific gene and allows you select changes to segregate out.  There are additional questions here (Does R882H == R882C?) but would be more general/purpose flexible at the expense of adding some complexity.

It's possible that we implement 1 to start and keep 2 as a future goal

**Comment by saimukund20** [comment]
Done.
